### ISSUE TITLE
Question on "mask"

### ISSUE THREAD

**Issue by fujistoo** [hasan1292/mDDPM#1]
Hi! Awesome work you've done here :) 

What exactly does `batch["mask"]` refer to? I went through the `create_dataset.py` and noticed that you created the mask yourself if no masks are available. I'm quite new on scalar images / medical datasets, so wasn't sure what does that mean. 

On the contrary, if I'd like to test this on other non-medical datasets, i.e. VisA, how should I modify these lines [here](https://github.com/hasan1292/mDDPM/blob/fe95d1264d24b85645bf0e701746220de55f1bbb/src/models/mDDPM.py#LL150C52-L150C52)? Realistically, my datamodule would contain `batch["image"]` as the input (healthy image) and also some ground-truth masks paired with "unhealthy" images for testing.

**Comment by hasan1292** [comment]
Hi. That one is just in case the mask is not given. It will create a mask on run-time. However, if you provide the mask, that condition will not be used.
